version: "3.8"
services:
  php:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: mentes-libres
    restart: always
    ports: 
      - 8080:80
    volumes:
      - ./src:/var/www/html
volumes:
  html: {}